<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LibroSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            [
                'title'     => 'Cien Años de Soledad',
                'author'    => 'Gabriel García Márquez',
                'editorial' => 'Random House',
                'year'      => 1967,
                'genre_id'  => 2,
                'synopsis'  => 'En el corazón de América Latina, el coronel José Arcadio Buendía funda Macondo, un pueblo aislado del mundo que crece y se transforma a lo largo de siete generaciones de su familia. A través de amores imposibles, guerras civiles interminables, plagas del olvido y lluvias de mariposas amarillas, García Márquez teje una épica donde lo sobrenatural convive con lo cotidiano. Personajes condenados a repetir sus errores, mujeres de belleza devastadora y hombres obsesionados por descifrar los manuscritos del gitano Melquíades conforman este universo donde el tiempo es circular y el destino, inevitable. Una obra cumbre de la literatura universal que redefine los límites entre la realidad y la fantasía.',
                'ISBN'      => '9788439745358',
                'image'     => 'https://imagessl8.casadellibro.com/a/l/s7/58/9788439745358.webp',
            ],
            [
                'title'     => 'El Nombre de la Rosa',
                'author'    => 'Umberto Eco',
                'editorial' => 'Lumen',
                'year'      => 1980,
                'genre_id'  => 3,
                'synopsis'  => 'En el otoño de 1327, el fraile franciscano Guillermo de Baskerville llega junto a su joven novicio Adso de Melk a una poderosa abadía benedictina del norte de Italia para asistir a una delicada reunión teológica. Antes de que comience, un monje aparece muerto en circunstancias inexplicables, y pronto los cadáveres se van acumulando siguiendo una lógica que parece extraída del Apocalipsis. Guillermo, de mente brillante y método casi detectivesco, se adentra en el laberíntico scriptorium y en la biblioteca prohibida de la abadía buscando una verdad que muchos quieren ocultar a cualquier precio. Eco construye un apasionante thriller medieval donde la fe, el conocimiento, el poder de los libros y la intolerancia chocan en una conclusión inolvidable.',
                'ISBN'      => '9788426403568',
                'image'     => 'https://imagessl8.casadellibro.com/a/l/s7/68/9788426403568.webp',
            ],
            [
                'title'     => '1984',
                'author'    => 'George Orwell',
                'editorial' => 'Minotauro',
                'year'      => 1949,
                'genre_id'  => 2,
                'synopsis'  => 'En 1984, los ciudadanos de Londres ya no distinguen entre el aspecto privado y público de sus vidas. Empleando sus técnicas de vigilancia sobre la población, el Gran Hermano les ha arrebatado la intimidad. Winston Smith es un funcionario cuyo trabajo consiste en escribir y reescribir la historia para el Ministerio de la Verdad, una de las instituciones del estado totalitario que subyuga al ciudadano. Un día, Smith siente que ya no quiere formar parte de los engranajes del sistema opresivo',
                'ISBN'      => ' 9788445010273',
                'image'     => 'https://imagessl3.casadellibro.com/a/l/s7/73/9788445010273.webp',
            ],
            [
                'title'     => 'Don Quijote de la Mancha',
                'author'    => 'Miguel de Cervantes',
                'editorial' => 'ALEAGUARA',
                'year'      => 1605,
                'genre_id'  => 1,
                'synopsis'  => 'Alonso Quijano, un hidalgo manchego de mediana edad, enloquece tras leer incansablemente libros de caballerías y decide transformarse en el caballero andante Don Quijote de la Mancha. Acompañado de su fiel escudero Sancho Panza, un campesino ingenioso y pragmático, emprende tres salidas por los caminos de España en busca de aventuras y justicia. Confunde molinos de viento con gigantes, ventas con castillos y rebaños de ovejas con ejércitos enemigos. Entre la locura y la lucidez, Cervantes construye una profunda reflexión sobre la naturaleza humana, el idealismo, la amistad y la diferencia entre ilusión y realidad. Considerada la primera novela moderna de la literatura occidental.',
                'ISBN'      => '9788420479873',
                'image'     => 'https://imagessl3.casadellibro.com/a/l/s7/73/9788420479873.webp',
            ],
            [
                'title'     => 'Harry Potter y la piedra filosofal',
                'author'    => 'J.K. Rowling',
                'editorial' => 'Salamandra',
                'year'      => 1997,
                'genre_id'  => 4,
                'synopsis'  => 'Harry Potter es un niño huérfano que vive miserable y olvidado en casa de sus tíos, los Dursley, una familia mezquina y sin imaginación que lo trata como a un criado y lo obliga a dormir en el diminuto armario que hay bajo las escaleras. Todo cambia el día en que Harry cumple once años y recibe una carta con un mensaje que transformará su vida para siempre: ha sido admitido en el Colegio Hogwarts de Magia y Hechicería. Allí descubre que es un mago famoso en el mundo mágico, que sus padres no murieron en un accidente de tráfico sino a manos del temible Lord Voldemort, y que él mismo sobrevivió milagrosamente a la maldición asesina. Entre clases de pociones, vuelos en escoba, partidos de quidditch y la amistad inquebrantable de Ron Weasley y Hermione Granger, Harry deberá enfrentarse a un misterio oculto en las entrañas de Hogwarts que amenaza con devolver al poder a las fuerzas más oscuras del mundo mágico.',
                'ISBN'      => '9788478884452',
                'image'     => 'https://imagessl2.casadellibro.com/a/l/s7/52/9788478884452.webp',
            ],
            [
                'title'     => 'La Península de las Casas Vacías',
                'author'    => 'David Uclés',
                'editorial' => 'Siruela',
                'year'      => 2024,
                'genre_id'  => 2,
                'synopsis'  => 'He aquí la historia de la descomposición total de una familia, de la deshumanización de un pueblo, de la desintegración de un territorio y de una península de casas vacías.  La historia de un soldado que se raja la piel para dejar salir la ceniza acumulada, de un poeta que cose la sombra de una niña tras un bombardeo, y de un maestro que enseña a sus alumnos a hacerse los muertos; de un general que duerme junto a la mano cortada de una santa, de un niño ciego que recupera la vista durante un apagón, y de una campesina que pinta de negro todos los árboles de su huerto; de un fotógrafo extranjero que pisa una mina cerca de Brunete y no levanta el pie en cuarenta años, de un gernikarra que conduce hasta el centro de París una camioneta con los restos humeantes de un ataque aéreo, y de un perro herido cuya sangre teñirá la última franja de una bandera abandonada en Badajoz.  He aquí pues la historia total de la Guerra Civil española y de una Iberia agonizante donde lo fantástico apuntala la crudeza de lo real; donde los anónimos miembros de un extenso clan de olivareros de Jándula cruzan sus destinos con los de Alberti, Lorca y Unamuno; Rodoreda, Zambrano y Kent; Hemingway, Orwell y Bernanos; Picasso y Mallo; Azaña y Foxá; donde lo épico y lo costumbrista se entrelazan para tejer un portentoso tapiz, poético y grotesco, bello y delirante.',
                'ISBN'      => '9788419942319',
                'image'     => 'https://imagessl9.casadellibro.com/a/l/s7/19/9788419942319.webp',
            ],
            [
                'title'     => 'Los Juegos del Hambre',
                'author'    => 'Suzzane Collins',
                'editorial' => 'Molino',
                'year'      => 2008,
                'genre_id'  => 6,
                'synopsis'  => 'Los Juegos del Hambre transcurren en Panem, una nación distópica dividida en doce distritos pobres controlados por un Capitolio opulento y cruel. Como castigo por una antigua rebelión, cada año dos jóvenes de cada distrito son seleccionados para luchar a muerte en una arena televisada. La protagonista es Katniss Everdeen, una chica del Distrito 12 que se ofrece voluntaria para sustituir a su hermana pequeña cuando esta es seleccionada. Junto a ella va Peeta Mellark, el hijo del panadero, quien declara públicamente estar enamorado de Katniss generando una estrategia mediática que los convierte en favoritos del público. Dentro de la arena, Katniss debe usar todas sus habilidades de cazadora para sobrevivir mientras navega entre alianzas peligrosas y sentimientos confusos hacia Peeta. Cuando al final solo quedan ellos dos, el Capitolio revoca la regla que permitía dos ganadores, obligándoles a enfrentarse. En un acto de rebeldía, Katniss propone que ambos coman bayas venenosas a la vez, forzando al Capitolio a aceptar dos ganadores para evitar quedarse sin ninguno. Este gesto aparentemente pequeño se convierte en la chispa que enciende la esperanza de la revolución en todos los distritos. La historia es una crítica feroz a los regímenes totalitarios, los medios de comunicación como herramienta de control y la desigualdad social extrema. Una saga que engancha desde la primera página y que va mucho más allá de una simple historia de supervivencia.',
                'ISBN'      => '9788427202122',
                'image'     => 'https://imagessl2.casadellibro.com/a/l/s7/22/9788427202122.webp',
            ],
            [
                'title'     => 'Así hablo Zaratustra',
                'author'    => 'Friedrich Nietzsche',
                'editorial' => 'Editorial Verbum',
                'year'      => 1896,
                'genre_id'  => 7,
                'synopsis'  => 'Cuando Zaratustra cumple treinta años, decide abandonar su hogar y retirarse a la montaña, donde pasa una década en completa soledad reflexionando sobre la naturaleza humana y el sentido de la existencia. Al cabo de ese tiempo, su sabiduría se ha vuelto tan grande que siente la necesidad de compartirla con el mundo y desciende al valle para hablar a los hombres. Es entonces cuando proclama una de sus ideas más célebres y provocadoras: Dios ha muerto, y con él han muerto también los valores absolutos que durante siglos habían guiado a la humanidad. Ante ese vacío, Zaratustra propone el concepto del Superhombre, un ser humano que supera sus limitaciones, crea sus propios valores y abraza la vida sin miedo ni resentimiento. Sin embargo, los hombres comunes no están preparados para escuchar su mensaje y lo reciben con indiferencia o incomprensión, lo que le genera una profunda soledad y frustración. A lo largo del libro, Zaratustra habla sobre el eterno retorno, la idea de que todo lo que ha ocurrido se repetirá infinitamente, y que aceptar eso con alegría es la máxima afirmación de la vida. También critica duramente la moral tradicional, la religión y el conformismo, a los que considera enemigos del verdadero crecimiento humano.',
                'ISBN'      => '9788413370200',
                'image'     => 'https://imagessl0.casadellibro.com/a/l/s7/00/9788413370200.webp',
            ],
            [
                'title'     => 'Agujeros Negros',
                'author'    => 'Stephen Hawking',
                'editorial' => 'Crítica',
                'year'      => 1988,
                'genre_id'  => 8,
                'synopsis'  => 'Los agujeros negros son regiones del espacio donde la gravedad es tan extrema que ni la luz puede escapar de ellas. Hawking explica que se forman principalmente cuando una estrella masiva agota su combustible y colapsa sobre sí misma bajo su propia gravedad. El libro describe el horizonte de sucesos, que es el límite invisible a partir del cual nada puede regresar, y la singularidad, el punto central donde las leyes de la física dejan de funcionar. Uno de los conceptos más fascinantes que presenta es la radiación de Hawking, su propio descubrimiento, que demuestra que los agujeros negros no son completamente negros sino que emiten una pequeña cantidad de energía. Esto fue revolucionario porque nadie antes había conseguido unir la mecánica cuántica con la relatividad general de forma tan elegante. El libro también aborda la paradoja de la información, que plantea si los datos sobre la materia que cae en un agujero negro se pierden para siempre o se conservan de algún modo. Hawking defiende que la información no se destruye, aunque explicar cómo se conserva sigue siendo uno de los grandes misterios de la física. A lo largo del libro, Hawking consigue explicar conceptos tremendamente complejos de forma accesible para cualquier lector sin conocimientos científicos previos. Es una obra que cambia completamente la forma en que uno percibe el espacio, el tiempo y los límites del conocimiento humano. Sin duda, uno de los libros de divulgación científica más importantes y apasionantes jamás escritos.',
                'ISBN'      => '9788491998754',
                'image'     => 'https://imagessl4.casadellibro.com/a/l/s7/54/9788491998754.webp',
            ],
            [
                'title'     => 'La Sombra del Viento',
                'author'    => 'Carlos Ruiz Zafón',
                'editorial' => 'Planeta',
                'year'      => 2001,
                'genre_id'  => 5,
                'synopsis'  => 'En la Barcelona de la posguerra, el joven Daniel Sempere es conducido por su padre al misterioso Cementerio de los Libros Olvidados, donde elige un ejemplar de una novela titulada La Sombra del Viento, escrita por Julián Carax. Fascinado por la obra, Daniel intenta descubrir quién fue su autor, pero tropieza con una sombra oscura que lleva décadas destruyendo todos los libros de Carax. Entre callejones con niebla, amores prohibidos, secretos de familia y la amenaza de un personaje sin rostro llamado Laín Coubert, Daniel se adentra en un laberinto de misterio donde pasado y presente se funden en una historia apasionante sobre la memoria, la traición y el poder redentor de la literatura.',
                'ISBN'      => '9788408163350',
                'image'     => 'https://imagessl0.casadellibro.com/a/l/s7/50/9788408163350.webp',
            ],
            [
                'title'     => '101 Historias NBA',
                'author'    => 'Gonzalo Vázquez',
                'editorial' => 'Ediciones JC',
                'year'      => 2013,
                'genre_id'  => 10,
                'synopsis'  => 'Debajo de la habitual enumeración de nombres, números y títulos que acompañan a las crónicas NBA reposa el verdadero misterio de lo que el autor denomina ?inmenso teatro de hombres?, todo ese fascinante universo humano que enriquece la vida de cualquier competición. Historias de victorias y derrotas, de épica y fracaso, de estrategia y anécdota, ninguna de las cuales resulta casual en una obra que permite comprender y disfrutar el más sabroso legado del baloncesto americano.',
                'ISBN'      => '9788415448228',
                'image'     => 'https://imagessl8.casadellibro.com/a/l/s7/28/9788415448228.webp',
            ],
            [
                'title'     => 'Código Limpio',
                'author'    => 'Robert C. Martin',
                'editorial' => 'Anaya',
                'year'      => 2008,
                'genre_id'  => 12,
                'synopsis'  => 'Código limpio (Clean Code: A Handbook of Agile Software Craftsmanship), publicado en 2008 por Robert C. Martin, conocido como "Uncle Bob", es una obra fundamental para cualquier desarrollador que aspire a la excelencia técnica. El libro parte de una premisa radical: el código se lee mucho más de lo que se escribe, por lo que la legibilidad es su característica más valiosa. A través de consejos prácticos y principios de ingeniería de software, el autor enseña cómo transformar un código confuso y difícil de mantener en uno elegante y eficiente. Martin aborda temas críticos como la elección de nombres significativos para variables, la creación de funciones pequeñas que realicen una sola tarea y la importancia de evitar comentarios innecesarios que solo intentan explicar un mal diseño. También introduce conceptos esenciales como el manejo de errores, el desarrollo guiado por pruebas (TDD) y los principios SOLID, que permiten construir sistemas escalables y robustos. Para el autor, escribir código limpio no es solo una cuestión de técnica, sino de ética profesional y disciplina; es un arte que separa a los aficionados de los verdaderos artesanos del software. La obra se ha convertido en la biblia de la programación moderna porque entiende que el éxito de un proyecto no depende solo de que el código funcione, sino de que sea lo suficientemente claro para que otros humanos puedan entenderlo y modificarlo sin miedo. Es, en definitiva, un manifiesto sobre la responsabilidad de los desarrolladores para evitar la degradación del software y garantizar la longevidad de los sistemas que construyen hoy.',
                'ISBN'      => '9788441532106',
                'image'     => 'https://imagessl6.casadellibro.com/a/l/s7/06/9788441532106.webp',
            ],
            [
                'title'     => 'EL Hobbit',
                'author'    => 'J. R. R. Tolkien',
                'editorial' => 'Minotauro',
                'year'      => 1937,
                'genre_id'  => 11,
                'synopsis'  => 'Bilbo Bolsón es un hobbit que disfruta de una vida apacible en la Comarca hasta que el mago Gandalf y trece enanos liderados por Thorin Escudo de Roble lo reclutan como saqueador para una misión épica: recuperar el Reino bajo la Montaña y su tesoro, custodiados por el temible dragón Smaug. A lo largo de un viaje lleno de peligros, Bilbo atraviesa las Montañas Nubladas, se enfrenta a trolls, orcos y arañas gigantes, y descubre una valentía inesperada que lo transforma profundamente. El momento más trascendental ocurre cuando, perdido en las profundidades de la tierra, encuentra un anillo mágico tras ganar un duelo de acertijos contra la criatura Gollum. Finalmente, tras llegar a la Montaña Solitaria y enfrentarse al dragón, Bilbo debe jugar un papel crucial en la Batalla de los Cinco Ejércitos, donde se decide el destino del tesoro y la paz en la Tierra Media, regresando a casa como un individuo muy diferente, poseedor de un secreto que cambiará la historia del mundo para siempre.',
                'ISBN'      => '9788445077948',
                'image'     => 'https://imagessl8.casadellibro.com/a/l/s7/48/9788445077948.webp',
            ],
            [
                'title'     => 'Romancero Gitano',
                'author'    => 'Federico García Lorca',
                'editorial' => 'Lunwerg Editores',
                'year'      => 1928,
                'genre_id'  => 13,
                'synopsis'  => 'El Romancero gitano, publicado en 1928, representa la cima poética de Federico García Lorca y es una de las obras más influyentes de la literatura en español. A través de dieciocho romances, el autor construye un universo donde la tradición popular andaluza se entrelaza con el surrealismo y la metáfora vanguardista. La obra no es un estudio costumbrista, sino una mitificación del pueblo gitano, al que Lorca eleva a la categoría de héroe trágico que lucha contra la represión, el destino fatal y la muerte. El libro está dominado por la "pena negra", un sentimiento de angustia existencial que persigue a sus personajes. Los poemas están cargados de símbolos icónicos: la luna como mensajera de la muerte, el metal que vaticina violencia y el color verde que evoca la fatalidad. Desde el rapto infantil en el "Romance de la luna, luna" hasta el deseo frustrado en el "Romance sonámbulo", Lorca explora la libertad y el dolor humano frente a la rigidez del mundo moderno. La presencia de la Guardia Civil simboliza el choque eterno entre la libertad instintiva del alma gitana y el orden represivo de la civilización. Es un canto a la Andalucía profunda y mítica, donde la belleza y la tragedia caminan siempre de la mano bajo una luz nocturna y misteriosa que ha cautivado a generaciones por su intensidad lírica, transformando lo local en un símbolo universal de la lucha humana contra un destino inevitable y cruel.',
                'ISBN'      => '9788417858407',
                'image'     => 'https://imagessl7.casadellibro.com/a/l/s7/07/9788417858407.webp',
            ],
            [
                'title'     => 'El Discurso del Método',
                'author'    => 'René Descartes',
                'editorial' => 'Alma',
                'year'      => 1637,
                'genre_id'  => 7,
                'synopsis'  => 'El Discurso del método, publicado en 1637 por René Descartes, es una de las obras fundamentales de la filosofía moderna y el punto de partida del racionalismo. Escrita originalmente en francés para ser accesible a todo el mundo, la obra propone un camino para dirigir la razón y buscar la verdad en las ciencias. Descartes comienza cuestionando todo el conocimiento heredado de la tradición y los sentidos, estableciendo la duda metódica como herramienta esencial. A través de este proceso, llega a su primera certeza indudable: "Pienso, luego existo" (Cogito, ergo sum), base sobre la cual reconstruye todo el saber. El libro se divide en seis partes donde detalla las reglas de su método —evidencia, análisis, síntesis y comprobación—, además de proponer una moral provisional para actuar mientras se duda. También aborda temas científicos y la existencia de Dios y el alma. Su enfoque rompió con la escolástica medieval, poniendo al sujeto y su capacidad racional en el centro del pensamiento humano, marcando así el inicio de la ciencia y la subjetividad modernas con una claridad expositiva que cambió la historia del pensamiento occidental para siempre.',
                'ISBN'      => '9788418395239',
                'image'     => 'https://imagessl9.casadellibro.com/a/l/s7/39/9788418395239.webp',
            ],
            [
                'title'     => 'Requiem por un Campesino Español',
                'author'    => 'Ramón J.Sender',
                'editorial' => 'Austral',
                'year'      => 1953,
                'genre_id'  => 11,
                'synopsis'  => 'Réquiem por un campesino español, la obra maestra de Ramón J. Sender originalmente titulada Mosén Millán, es una pieza clave de la literatura de la posguerra que condensa la tragedia de la Guerra Civil Española en un entorno rural. La narración se sitúa en un pueblo aragonés donde el sacerdote Mosén Millán espera para celebrar una misa de réquiem por el alma de Paco el del Molino, un joven campesino al que bautizó, casó y, finalmente, traicionó. Mientras el cura espera, sus recuerdos reconstruyen la vida de Paco: su infancia, su toma de conciencia social y su lucha por la justicia agraria que lo llevó a enfrentarse a los terratenientes. A través de un ritmo pausado y simbólico, la novela explora la culpa, la responsabilidad de la Iglesia y la ruptura de los lazos humanos bajo la presión del fascismo. El romance que el monaguillo canta en el fondo sirve como contrapunto trágico, elevando la figura de Paco a la categoría de mito popular. La obra es una denuncia desgarradora sobre la pasividad de los poderosos y el sacrificio de los inocentes en un conflicto que dividió pueblos y conciencias, dejando una herida abierta en la memoria histórica que aún resuena por su crudeza y honestidad narrativa, mostrando cómo la traición de quienes debían proteger al pueblo marcó el destino de toda una nación sumida en el silencio y el remordimiento.',
                'ISBN'      => '9788423361014',
                'image'     => 'https://imagessl4.casadellibro.com/a/l/s7/14/9788423361014.webp',
            ],
            [
                'title'     => 'Campos de Castilla',
                'author'    => 'Antonio Machado',
                'editorial' => 'Cátedra',
                'year'      => 1912,
                'genre_id'  => 13,
                'synopsis'  => 'Campos de Castilla, publicado originalmente en 1912 por Antonio Machado, es la obra cumbre de la Generación del 98 y refleja el profundo giro del autor hacia una poesía más objetiva, histórica y social. Tras su llegada a Soria, Machado queda cautivado por la dureza y la sobriedad del paisaje castellano, el cual utiliza como un espejo para proyectar su propia alma y la decadencia de una España estancada en su pasado. El poemario transita desde la descripción lírica de las tierras del Duero hasta la amarga meditación sobre el carácter español, marcado por la envidia y el casticismo. En esta edición se incluye el extenso romance "La tierra de Alvargonzález", que explora la violencia y el mito del fratricidio. Sin embargo, el tono del libro se vuelve íntimo y desgarrador tras la muerte de su joven esposa, Leonor Izquierdo; los poemas dedicados a su pérdida transforman el paisaje real en un escenario de memoria y ausencia. La obra no solo es un homenaje a la geografía de Castilla, sino una crítica social que clama por una "España de la rabia y la idea" frente a la España "que bosteza". Con un lenguaje depurado y lleno de símbolos como la encina, el olmo y el camino, Machado logra elevar la realidad cotidiana a una dimensión trascendental, consolidando un retrato ético y estético que define la identidad nacional desde la melancolía y la esperanza de una regeneración espiritual que parece nunca llegar.',
                'ISBN'      => '9788437608662',
                'image'     => 'https://imagessl2.casadellibro.com/a/l/s7/62/9788437608662.webp',
            ],
            [
                'title'     => 'El Rayo que no Cesa',
                'author'    => 'Miguel Hernández',
                'editorial' => 'Espasa',
                'year'      => 1936,
                'genre_id'  => 13,
                'synopsis'  => 'El rayo que no cesa, publicado en 1936, es la obra más emblemática de Miguel Hernández y representa una de las cimas de la poesía amorosa en lengua española. A través de un dominio magistral del soneto, el poeta alicantino construye un cancionero desgarrador donde el amor es sentido como una fuerza fatal, una herida abierta y un rayo que castiga sin tregua el corazón del amante. El libro explora el deseo insatisfecho, la frustración y el dolor ante la imposibilidad de la unión plena, utilizando metáforas de gran fuerza física como el toro, el metal y el cuchillo. En esta obra, el sentimiento amoroso no es un refugio, sino un campo de batalla donde la pasión choca contra las barreras de la castidad y el destino. Uno de los momentos más altos del poemario es la "Elegía a Ramón Sijé", donde el dolor por la muerte del amigo se funde con la rabia y la ternura en versos inolvidables que trascienden el tema amoroso para abrazar el duelo existencial. Con un lenguaje que combina la perfección técnica del Siglo de Oro con la intensidad emocional del surrealismo, Hernández logra transmitir una sed de vida y amor que, pese a ser castigada por un rayo constante de sufrimiento, nunca se apaga. La obra es, en esencia, el retrato de un hombre que se debate entre la luz de la pasión y la sombra de la tragedia, convirtiendo su tormento personal en un grito universal de resistencia emocional que ha quedado grabado como el testamento de un poeta que amó y sufrió con una honestidad literaria absolutamente arrolladora.',
                'ISBN'      => '9788467082104',
                'image'     => 'https://imagessl4.casadellibro.com/a/l/s7/04/9788467082104.webp',
            ],
            [
                'title'     => 'La Primera Guerra Mundial Contada para Escépticos',
                'author'    => 'Juan Eslava Galán',
                'editorial' => 'Planeta',
                'year'      => 2014,
                'genre_id'  => 14,
                'synopsis'  => 'La Primera Guerra Mundial contada para escépticos, de Juan Eslava Galán, es una crónica amena y desmitificadora de la Gran Guerra que huye de la densidad académica para centrarse en el lado más humano y curioso del conflicto. La obra comienza en 1914, cuando una Europa en plenitud técnica y científica se ve arrastrada a un efecto dominó por el asesinato del archiduque Francisco Fernando en Sarajevo. A través de su característico estilo divulgativo impregnado de ironía, el autor narra cómo un hecho aislado envolvió a más de cincuenta países en una carnicería sin precedentes. El lector recorre la historia no solo a través de batallas y pactos, sino mediante episodios singulares: el tren sellado de Lenin, las costumbres en los burdeles de campaña, los espías en hoteles de lujo y los pasatiempos de la tropa en las trincheras. Eslava Galán desmonta mitos y explica con sencillez las causas políticas y sociales, como el genocidio armenio o el papel de la mujer, sin perder el rigor histórico. Es un relato coral que humaniza a los protagonistas y revela las miserias de la contienda, permitiendo comprender cómo aquel desastre sembró las semillas de la Segunda Guerra Mundial. La obra destaca por su capacidad de conectar con el lector actual, utilizando el humor y la anécdota para iluminar uno de los hitos más oscuros y transformadores del siglo XX, convirtiendo la historia en algo vivo, cercano y profundamente revelador para cualquier mente curiosa.',
                'ISBN'      => '9788408124535',
                'image'     => 'https://imagessl5.casadellibro.com/a/l/s7/35/9788408124535.webp',
            ],
            [
                'title'     => 'Romeo y Julieta',
                'author'    => 'William Shakespeare',
                'editorial' => 'Austral',
                'year'      => 1597,
                'genre_id'  => 15,
                'synopsis'  => 'Romeo y Julieta, la tragedia más célebre de William Shakespeare, narra la historia de dos jóvenes amantes que desafían el odio ancestral entre sus familias, los Montesco y los Capuleto, en la ciudad de Verona. El destino los une en un baile de máscaras donde el flechazo es instantáneo y absoluto, llevándolos a un matrimonio secreto orquestado por Fray Lorenzo con la esperanza de reconciliar a los clanes. Sin embargo, la violencia urbana y una cadena de malentendidos fatales precipitan el desastre: tras el exilio de Romeo y un plan desesperado de Julieta para fingir su propia muerte, la falta de comunicación conduce a un doble suicidio en la cripta familiar. Este sacrificio final logra finalmente la paz entre los padres, pero a un coste devastador. La obra explora la tensión entre el libre albedrío y el destino, utilizando un lenguaje poético sublime que ha convertido a sus protagonistas en el símbolo universal del amor romántico y su capacidad para trascender incluso la muerte. Es un retrato crudo de cómo el odio de los adultos consume la juventud y la inocencia, dejando una lección eterna sobre la importancia del perdón y la mediación frente a la intransigencia. A través de sus personajes, Shakespeare captura la intensidad del deseo adolescente y la fragilidad de la vida, logrando que esta pieza del siglo XVI siga resonando con la misma fuerza emocional en la actualidad, recordándonos que el amor, aunque sea una fuerza luminosa, a menudo es víctima de las sombras de una sociedad dividida por prejuicios antiguos.',
                'ISBN'      => '9788467043655',
                'image'     => 'https://imagessl5.casadellibro.com/a/l/s7/55/9788467043655.webp',
            ],
        ];

        DB::table('libros')->insert($books);
    }
}
